name: Build WotW Rando

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (leave empty to build only)'
        required: false
        default: '5.0.0-alpha.'
      client_branch:
        description: 'Client branch'
        required: true
        default: 'v5'
      ui_branch:
        description: 'UI branch'
        required: true
        default: 'v5'
      seedgen_branch:
        description: 'Seedgen branch'
        required: true
        default: 'v5'

permissions:
  packages: write
  contents: write

jobs:
  build_client:
    runs-on: windows-2025
    env:
      SCCACHE_GHA_ENABLED: "true"
      USERNAME: ori-community
      VCPKG_EXE: C:/vcpkg/vcpkg
      FEED_URL: https://nuget.pkg.github.com/ori-community/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/ori-community/index.json,readwrite"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install CMake
        run: choco install cmake
      - name: Install Ninja
        run: choco install ninja
      - name: Enable Git support for long file paths
        run: git config --system core.longpaths true
      - name: Set up directories
        run: |
          md -Path 'C:\\moon\\randomizer\\client'
      - name: Clone ori-community/wotw-rando-client
        run: |
          git clone --branch ${{ github.event.inputs.client_branch || 'dev' }} --depth 1 https://github.com/ori-community/wotw-rando-client.git
          cd wotw-rando-client
          git rev-parse HEAD > C:\moon\randomizer\client\client.revision
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/github-script@v8
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Update vcpkg repository
        shell: cmd
        run: |
          cd /d C:\vcpkg
          git pull
          .\bootstrap-vcpkg.bat
      - name: Add NuGet sources
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"
      - name: Generate CMake project
        shell: cmd
        working-directory: wotw-rando-client
        run: "generate-cmake.release-ninja.bat"
      - name: Compile Wotw Rando
        shell: cmd
        working-directory: wotw-rando-client
        run: |
          cmake --build cmake-build-relwithdebinfo --target INSTALL_RUNTIME --config RelWithDebInfo
          IF ERRORLEVEL 1 (
            echo BUILD FAILED
            exit 1
          )
      - name: Write Run ID
        shell: bash
        run: |
          echo -n "${{ github.run_id }}" > /c/moon/randomizer/run_id
      - name: Copy modloader_config.json
        shell: cmd
        working-directory: wotw-rando-client
        run: |
          copy resources\modloader_config.json C:\moon\randomizer\client\modloader_config.json
      - name: Clone ori-community/wotw-rando-assets
        run: |
          git clone --depth 1 https://github.com/ori-community/wotw-rando-assets.git C:\moon\randomizer\client\assets
          git -C C:\moon\randomizer\client\assets rev-parse HEAD > C:\moon\randomizer\client\assets.revision
          git -C C:\moon\randomizer\client\assets lfs checkout
          Remove-Item -Path C:\moon\randomizer\client\assets\.git -Force -Recurse
      - name: Archive randomizer
        uses: actions/upload-artifact@v6
        with:
          name: client
          include-hidden-files: true
          path: |
            C:\moon\randomizer\client\**\*
            !C:\moon\randomizer\client\*.pdb
            !C:\moon\randomizer\client\*.lib
          retention-days: 1
      - name: Archive PDBs
        uses: actions/upload-artifact@v6
        with:
          name: pdb
          path: |
            C:\moon\randomizer\client\*.pdb
  


  build_seedgen_windows:
    runs-on: windows-2025
    steps:
      - name: Set up directories
        run: "md -Path 'C:\\seedgen'"
      - name: Clone ori-community/wotw-seedgen
        run: |
          git clone --branch ${{ github.event.inputs.seedgen_branch || 'dev' }} --depth 1 https://github.com/ori-community/wotw-seedgen.git .
          git rev-parse HEAD > C:\seedgen\seedgen.revision
      - name: Install Rust (Stable)
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Build seedgen
        run: |
          cargo build --release
      - name: Copy artifacts
        shell: powershell
        run: |
          echo Copying seedgen.exe
          Copy-Item -Path ".\target\release\wotw-seedgen.exe" -Destination "C:\seedgen\wotw-seedgen.exe"
          echo Copying headers and presets
          Copy-Item -Path assets\* -Recurse -Destination C:\seedgen\
      - name: Archive seedgen
        uses: actions/upload-artifact@v6
        with:
          name: seedgen_windows
          include-hidden-files: true
          path: 'C:\seedgen\**\*'
          retention-days: 1
  build_seedgen_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up directories
        run: "mkdir /tmp/seedgen"
      - name: Clone ori-community/wotw-seedgen
        run: |
          git clone --branch ${{ github.event.inputs.seedgen_branch || 'dev' }} --depth 1 https://github.com/ori-community/wotw-seedgen.git .
          git rev-parse HEAD > /tmp/seedgen/seedgen.revision
      - name: Install Rust (Stable)
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Build seedgen
        run: |
          cargo build --release
      - name: Copy artifacts
        run: |
          cp -v target/release/wotw-seedgen /tmp/seedgen/wotw-seedgen
          cp -vr assets/* /tmp/seedgen/
      - name: Archive seedgen
        uses: actions/upload-artifact@v6
        with:
          name: seedgen_linux
          include-hidden-files: true
          path: '/tmp/seedgen/**/*'
          retention-days: 1

  build_launcher_windows:
    runs-on: windows-2025
    steps:
      - name: Clone ori-community/rando-ui
        run: |
          git clone --branch ${{ github.event.inputs.ui_branch || 'dev' }} --depth 1 https://github.com/ori-community/rando-ui .

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache-dependency-path: |
            ./launcher/package-lock.json
            ./shared/package-lock.json
            ./web/package-lock.json
          cache: npm

      - name: Install launcher dependencies
        run: npm ci
        working-directory: ./launcher

      - name: Install shared dependencies
        run: npm ci
        working-directory: ./shared

      - name: Install web dependencies
        run: npm ci
        working-directory: ./web

      - name: Generate static web assets
        working-directory: ./web
        run: |
          npm run generate
          Copy-item -Force -Recurse -Verbose ".\dist\*" -Destination "..\launcher\web-build\"

      - run: npm run package
        working-directory: ./launcher

      - name: Write Git revision
        run: |
          git rev-parse HEAD > ".\launcher\out\Ori and the Will of the Wisps Randomizer-win32-x64\launcher.revision"

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: launcher_windows
          retention-days: 1
          include-hidden-files: true
          path: |
            .\launcher\out\Ori and the Will of the Wisps Randomizer-win32-x64\*


  build_launcher_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ori-community/rando-ui
        run: |
          git clone --branch ${{ github.event.inputs.ui_branch || 'dev' }} --depth 1 https://github.com/ori-community/rando-ui .

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache-dependency-path: |
            ./launcher/package-lock.json
            ./shared/package-lock.json
            ./web/package-lock.json
          cache: npm

      - name: Install launcher dependencies
        run: npm ci
        working-directory: ./launcher

      - name: Install shared dependencies
        run: npm ci
        working-directory: ./shared

      - name: Install web dependencies
        run: npm ci
        working-directory: ./web

      - name: Generate static web assets
        working-directory: ./web
        run: |
          npm run generate
          cp -vr ./dist/* ../launcher/web-build/

      - run: npm run package
        working-directory: ./launcher

      - name: Write Git revision
        run: |
          git rev-parse HEAD > "./launcher/out/Ori and the Will of the Wisps Randomizer-linux-x64/launcher.revision"

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: launcher_linux
          retention-days: 1
          include-hidden-files: true
          path: |
            ./launcher/out/Ori and the Will of the Wisps Randomizer-linux-x64/*


  render_credits:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ori-community/wotw-rando-credits
        run: |
          git clone --depth 1 https://github.com/ori-community/wotw-rando-credits .
          git rev-parse HEAD > credits.revision

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Render credits
        run: npm run generate

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: credits
          retention-days: 1
          path: |
            ./credits
            ./credits.revision



  build_windows_installer:
    runs-on: windows-2025
    needs: [build_client, build_seedgen_windows, build_launcher_windows, render_credits]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Inno setup
        run: |
          winget install --id JRSoftware.InnoSetup -e -s winget --force --uninstall-previous --silent --location C:\Inno

      - name: Set up directories
        run: |
          md -Path 'C:\\_installer_root\\client'
          md -Path 'C:\\_installer_root\\seedgen'

      - name: Download launcher
        uses: actions/download-artifact@v7
        with:
          name: launcher_windows
          path: "C:\\_installer_root\\"
      - name: Download client
        uses: actions/download-artifact@v7
        with:
          name: client
          path: "C:\\_installer_root\\client\\"
      - name: Download seedgen
        uses: actions/download-artifact@v7
        with:
          name: seedgen_windows
          path: "C:\\_installer_root\\seedgen\\"
      - name: Download credits
        uses: actions/download-artifact@v7
        with:
          name: credits
          path: "C:\\_installer_root\\client\\"
      - name: Write version file
        shell: bash
        run: |
          echo Writing version file...
          (if [[ -n "${{ github.event.inputs.release_version }}" ]]; then echo -n "${{ github.event.inputs.release_version }}"; else echo -n "develop"; fi) > randomizer_version
          cp -f randomizer_version /c/_installer_root/randomizer_version

      - name: Build installer
        run: |
          $env:APP_VERSION = "${{ github.event.inputs.release_version || 'dev' }}"
          $env:INSTALLER_ROOT = 'C:\\_installer_root'
          & 'C:\Inno\ISCC.exe' /O"output" /F"WotwRandomizerSetup" setup.iss

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: windows_installer
          retention-days: 7
          path: |
            .\output\WotwRandomizerSetup.exe
  build_linux_appimage:
    runs-on: ubuntu-latest
    needs: [build_client, build_seedgen_linux, build_launcher_linux, render_credits]
    steps:
      - name: Install bsdtar
        run: sudo apt-get -y install libarchive-tools

      - name: Clone ori-community/wotw-randomizer-appimage
        run: |
          git clone --depth 1 https://github.com/ori-community/wotw-randomizer-appimage .

      - name: Set up directories
        run: |
          mkdir -p appdir/opt/wotw-randomizer/client
          mkdir -p appdir/opt/wotw-randomizer/seedgen

      - name: Download launcher
        uses: actions/download-artifact@v7
        with:
          name: launcher_linux
          path: "appdir/opt/wotw-randomizer/"
      - name: Download client
        uses: actions/download-artifact@v7
        with:
          name: client
          path: "appdir/opt/wotw-randomizer/client/"
      - name: Download seedgen
        uses: actions/download-artifact@v7
        with:
          name: seedgen_linux
          path: "appdir/opt/wotw-randomizer/seedgen/"
      - name: Download credits
        uses: actions/download-artifact@v7
        with:
          name: credits
          path: "appdir/opt/wotw-randomizer/client/"

      - name: Make executables executable
        run: |
          chmod +x "appdir/opt/wotw-randomizer/seedgen/wotw-seedgen"
          chmod +x "appdir/opt/wotw-randomizer/Ori and the Will of the Wisps Randomizer"

      - name: Write version file
        run: |
          echo Writing version file...
          (if [[ -n "${{ github.event.inputs.release_version }}" ]]; then echo -n "${{ github.event.inputs.release_version }}"; else echo -n "develop"; fi) > randomizer_version
          cp -f randomizer_version appdir/opt/wotw-randomizer/randomizer_version

      - name: Build AppImage
        run: ./build.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux_appimage
          retention-days: 7
          path: |
            *.AppImage

  build_linux_package:
    runs-on: ubuntu-latest
    needs: [build_client, build_seedgen_LINUX, build_launcher_linux, render_credits]
    steps:
      - name: Set up directories
        run: |
          mkdir -p /tmp/installer_root/client
          mkdir -p /tmp/installer_root/seedgen

      - name: Download launcher
        uses: actions/download-artifact@v7
        with:
          name: launcher_linux
          path: "/tmp/installer_root/"
      - name: Download client
        uses: actions/download-artifact@v7
        with:
          name: client
          path: "/tmp/installer_root/client/"
      - name: Download seedgen
        uses: actions/download-artifact@v7
        with:
          name: seedgen_linux
          path: "/tmp/installer_root/seedgen/"
      - name: Download credits
        uses: actions/download-artifact@v7
        with:
          name: credits
          path: "/tmp/installer_root/client/"

      - name: Write version file
        run: |
          echo Writing version file...
          (if [[ -n "${{ github.event.inputs.release_version }}" ]]; then echo -n "${{ github.event.inputs.release_version }}"; else echo -n "develop"; fi) > randomizer_version
          cp -f randomizer_version /tmp/installer_root/randomizer_version

      - name: Build package
        run: |
          cd /tmp/installer_root
          tar -zcvf /tmp/WotwRandomizer.tar.gz *

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: linux_package
          retention-days: 7
          path: |
            /tmp/WotwRandomizer.tar.gz

  create_release:
    runs-on: ubuntu-latest
    needs: [build_windows_installer, build_linux_appimage]
    if: ${{ github.event.inputs.release_version != '' }}
    steps:
      - name: Set up directories
        run: "mkdir -p /tmp/release"
      - name: Download Installer
        uses: actions/download-artifact@v7
        with:
          name: windows_installer
          path: "/tmp/release/"
      - name: Download Linux AppImage
        uses: actions/download-artifact@v7
        with:
          name: linux_appimage
          path: "/tmp/release/"
      - name: Download Linux Package
        uses: actions/download-artifact@v7
        with:
          name: linux_package
          path: "/tmp/release/"
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: TODO
          prerelease: false
          tag_name: ${{ github.event.inputs.release_version }}
          name: ${{ github.event.inputs.release_version }}
          files: |
            /tmp/release/WotwRandomizerSetup.exe
            /tmp/release/WotwRandomizer.tar.gz
            /tmp/release/WotwRandomizer.AppImage
